// chạy scripts
// npx ts-node scripts/e2e-tester/01-create-event.ts
// npx ts-node scripts/e2e-tester/02-assign-teams-and-submissions.ts


import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log("Starting 01-create-event.ts...");

    // Find an organizer/admin to be the creator
    const creator = await prisma.user.findFirst({
        where: { role: { in: ['organizer', 'admin'] } }
    });

    if (!creator) {
        console.error("No organizer or admin found. Please seed users first.");
        return;
    }

    // Prepare Event Data
    const eventName = `SEAL E2E Hackathon ${new Date().getTime()}`;
    const newEvent = await prisma.event.create({
        data: {
            name: eventName,
            description: "A comprehensive E2E test event generated by automation scripts. This hackathon is designed to push the boundaries of technology in AI and Web3.",
            season: 'Fall',
            year: 2026,
            status: 'active', // Active immediately to allow participation
            registrationDeadline: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000), // Deadline in 7 days
            startDate: new Date(),
            githubOrgUrl: 'https://github.com/DEMO-SEAL-HackaThon-ORG',
            prize1st: '$5,000 Cash + 10,000 AWS Credits',
            prize2nd: '$3,000 Cash + 5,000 AWS Credits',
            prize3rd: '$1,000 Cash + 2,000 AWS Credits',
            prizeHonorable: 'Exclusive Swag package + 1,000 AWS Credits',
            createdById: creator.id,

            // Create Tracks
            tracks: {
                create: [
                    { name: 'AI & Data Track', description: 'Focus on AI, ML, Data Science', maxTeams: 50, maxMembersPerTeam: 5 },
                    { name: 'Web3 & Blockchain', description: 'Focus on decentralization', maxTeams: 50, maxMembersPerTeam: 5 }
                ]
            },
        },
        include: { tracks: true }
    });

    // Create Rounds
    // Round 1: Separate by track (isTrackSpecific: true)
    await prisma.round.create({
        data: {
            eventId: newEvent.id,
            roundNumber: 1,
            name: "Vòng Sơ loại (Round 1)",
            status: 'open',
            submissionType: 'file',
            submissionDeadline: new Date(new Date().getTime() + 14 * 24 * 60 * 60 * 1000), // +14 days
            maxFileSizeMb: 50, // 50 MB
            isTrackSpecific: true,
        }
    });

    // Round 2: Global (isTrackSpecific: false)
    await prisma.round.create({
        data: {
            eventId: newEvent.id,
            roundNumber: 2,
            name: "Vòng Chung kết (Round 2)",
            status: 'not_started',
            submissionType: 'github_link',
            submissionDeadline: new Date(new Date().getTime() + 30 * 24 * 60 * 60 * 1000), // +30 days
            maxFileSizeMb: 20,
            isTrackSpecific: false,
        }
    });

    console.log(`Event Created Successfully: ${eventName}`);
    console.log(`Event ID: ${newEvent.id}`);
    console.log(`Tracks: ${newEvent.tracks.map(t => t.name).join(', ')}`);
}

main()
    .catch(e => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
